// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdgSAxoyFlZowKdtUlXIrsZFsJ7dx4_TA',
    appId: '1:742665283156:web:a0801675a0e63859306fc1',
    messagingSenderId: '742665283156',
    projectId: 'airken-e674a',
    authDomain: 'airken-e674a.firebaseapp.com',
    storageBucket: 'airken-e674a.appspot.com',
    measurementId: 'G-RBCEVFXZC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7N5S4xPDOSsd3iULkj1cAb87aDJsTDGI',
    appId: '1:742665283156:android:ddcb0cdbb22bc2ec306fc1',
    messagingSenderId: '742665283156',
    projectId: 'airken-e674a',
    storageBucket: 'airken-e674a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwTURsoo9p4UTbo1b2TaCO-I7ymOdYR1A',
    appId: '1:742665283156:ios:576b5ad00d6712a4306fc1',
    messagingSenderId: '742665283156',
    projectId: 'airken-e674a',
    storageBucket: 'airken-e674a.appspot.com',
    iosClientId: '742665283156-7ughmk5at53kp06q9rmu4ao63feodbal.apps.googleusercontent.com',
    iosBundleId: 'com.example.airken',
  );
}
